# -*- coding: utf-8 -*-
"""StreamlitappCNNbiLSTMAttentionArabic.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xBJ0l2hacq_wQpWgyLeGP9MCuh-3SwGp
"""

import streamlit as st
import numpy as np
import pandas as pd
import re
import nltk
from nltk.corpus import stopwords
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.preprocessing.sequence import pad_sequences
from keras.models import load_model

# Download stopwords for Arabic
nltk.download('stopwords')
stop_words = set(stopwords.words('arabic'))

# Load the tokenizer and model
tokenizer = keras.preprocessing.text.Tokenizer(num_words=5000)
model = load_model('model.h5')

# Function to preprocess text
def preprocess_text(text):
    text = re.sub(r'http\S+|www\S+|https\S+', '', text)  # Remove URLs
    text = re.sub(r'\@\w+|\#', '', text)  # Remove mentions and hashtags
    text = re.sub('[^ء-ي]', ' ', text)  # Remove non-Arabic characters
    text = ' '.join([word for word in text.split() if word not in stop_words])  # Remove stopwords
    return text

# Function to make predictions
def predict_sentiment(text):
    preprocessed_text = preprocess_text(text)
    sequence = tokenizer.texts_to_sequences([preprocessed_text])
    sequence = pad_sequences(sequence, padding='post', maxlen=100)
    prediction = model.predict(sequence)
    sentiment = "Positive" if prediction[0][0] > 0.5 else "Negative"
    return sentiment

# Streamlit app
def main():
    st.title("Arabic Sentiment Analysis")
    st.write("Enter your text below:")
    user_input = st.text_input("Text")
    
    if st.button("Predict"):
        sentiment = predict_sentiment(user_input)
        st.write("Sentiment:", sentiment)

if __name__ == "__main__":
    main()